<!DOCTYPE html>
<html>
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headLink() ?>
        <?php $this->headScript()->appendFile('/library/js/jquery.min.js'); ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="wrapper">
            <div id="header">
                <div id="logo">
                    <img src="/library/images/pinjoo.png" alt="Pinjoo" />
                </div>
                <div class="clear"></div>
            </div>
            <div id="navigation">
                <ul id="topnav">
                    <li><a href="#">Dashboard</a></li>
                </ul>
                
            </div>
            <div id="main-body">
                <?php echo $this->layout()->content ?>
            </div>
            
        </div>
    </body>
</html>